import {Books} from "../../src/home/Books";

export const BooksList: Array<Books> = [
   {
       name:"maths",
       discription: "it is simple problems book for children",
       author:"naveen",
       price: 5,
       pagecount: 1,
	   isbn:"",
	   id:1,
   },
   {
    name:"social",
    discription: "it is sample book for children",
    author:"naveen",
    price: 7,
    pagecount: 1,
	isbn:"",
	id:2,
},
{
    name:"telugu",
    discription: "it is language learning book",
    author:"naveen",
    price: 8,
    pagecount: 1,
	isbn:"",
	id:3,
},
{
    name:"English",
    discription: "it is international language learning book",
    author:"naveen",
    price: 5,
    pagecount: 1,
	isbn:"",
	id:4,
},
{
    name:"maths",
    discription: "it is simple problems book for children",
    author:"naveen",
    price: 5,
    pagecount: 1,
	isbn:"",
	id:5,
},
{
	name:"social",
	discription: "it is sample book for children",
	author:"naveen",
	price: 7,
	pagecount: 1,
	isbn:"",
	id:6,
},
{
	name:"telugu",
	discription: "it is language learning book",
	author:"naveen",
	price: 8,
	pagecount: 1,
	isbn:"",
	id:7,
},
{
	name:"English",
	discription: "it is international language learning book",
	author:"naveen",
	price: 5,
	pagecount: 1,
	isbn:"",
	id:8,
},
{
	name:"social",
	discription: "it is sample book for children",
	author:"naveen",
	price: 7,
	pagecount: 1,
	isbn:"",
	id:9,
},
{
	name:"telugu",
	discription: "it is language learning book",
	author:"naveen",
	price: 8,
	pagecount: 1,
	isbn:"",
	id:10,
},
{
	name:"English",
	discription: "it is international language learning book",
	author:"naveen",
	price: 5,
	pagecount: 1,
	isbn:"",
	id:11,
}
]